// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMfMsoqlxq7a_n_DTjMOV9mLU1Ht73rE',
    appId: '1:763498876461:android:b7ebe506d8453163f2f2a4',
    messagingSenderId: '763498876461',
    projectId: 'simple-crud-7dc79',
    databaseURL: 'https://simple-crud-7dc79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-crud-7dc79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKSTswrp8bX_4gbm7MAtujqQITiRBIz0',
    appId: '1:763498876461:ios:01d341a5cd71c7aef2f2a4',
    messagingSenderId: '763498876461',
    projectId: 'simple-crud-7dc79',
    databaseURL: 'https://simple-crud-7dc79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-crud-7dc79.appspot.com',
    iosClientId: '763498876461-bt9d5e8fpqgtrve4q330h4aaefnerqoh.apps.googleusercontent.com',
    iosBundleId: 'com.ihsanbagus.flutterxfirestore',
  );
}
